using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Google.Cloud.AIPlatform.V1;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static Google.Cloud.AIPlatform.V1.JobService;

[ApiController]
[Authorize]
[Route("api/[controller]")]
public class AvatarController : ControllerBase
{
    private readonly IConfiguration _configuration;
    private readonly PredictionServiceClient _predictionServiceClient;
    private readonly BlobServiceClient _blobServiceClient;
    private readonly ILogger<AvatarController> _logger;

    public AvatarController(IConfiguration configuration, ILogger<AvatarController> logger)
    {
        _configuration = configuration;
        _logger = logger;

        // Initialize Gemini AI client
        var geminiProjectId = _configuration["GeminiAI:ProjectId"];
        var geminiLocation = _configuration["GeminiAI:Location"] ?? "us-central1";

        var predictionServiceClientBuilder = new PredictionServiceClientBuilder
        {
            Endpoint = $"{geminiLocation}-aiplatform.googleapis.com"
        };
        _predictionServiceClient = predictionServiceClientBuilder.Build();

        // Initialize Azure Blob Storage client
        var storageConnectionString = _configuration["AzureStorage:ConnectionString"];
        _blobServiceClient = new BlobServiceClient(storageConnectionString);
    }

    [HttpPost("generate")]
    public async Task<IActionResult> GenerateAvatar([FromBody] AvatarRequest request)
    {
        try
        {
            _logger.LogInformation("Starting avatar generation using Gemini AI");

            // Generate image using Gemini AI
            var imageBytes = await GenerateImageWithGemini(request);

            // Upload to Azure Blob Storage
            var imageUrl = await UploadToAzureBlobStorage(imageBytes, $"{Guid.NewGuid()}.png");

            _logger.LogInformation("Avatar generated and stored successfully");

            return Ok(new AvatarResponse { ImageUrl = imageUrl });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating avatar");
            return StatusCode(500, new { error = ex.Message });
        }
    }

    private async Task<byte[]> GenerateImageWithGemini(AvatarRequest request)
    {
        var prompt = CreatePrompt(request);

        var generateContentRequest = new GenerateContentRequest
        {
            Model = $"projects/{_configuration["GeminiAI:ProjectId"]}/locations/{_configuration["GeminiAI:Location"] ?? "us-central1"}/publishers/google/models/{_configuration["GeminiAI:Model"] ?? "imagen-3.0-generate-002"}",
            Contents =
            {
                new Content
                {
                    Role = "USER",
                    Parts =
                    {
                        new Part
                        {
                            Text = prompt
                        }
                    }
                }
            },
            GenerationConfig = new GenerationConfig
            {
                Temperature = 0.4f,
                TopK = 32,
                TopP = 1,
                MaxOutputTokens = 2048,
            }
        };

        try
        {
            var response = await _predictionServiceClient.GenerateContentAsync(generateContentRequest);

            // Handle Gemini AI response - this depends on the specific model output
            // For image generation models, the response might contain image data
            if (response.Candidates.Count > 0 && response.Candidates[0].Content.Parts.Count > 0)
            {
                var responseText = response.Candidates[0].Content.Parts[0].Text;

                // If the response contains base64 image data
                if (responseText.Contains("data:image"))
                {
                    var base64Data = responseText.Split(',')[1];
                    return Convert.FromBase64String(base64Data);
                }

                // For models that return direct image bytes (this might need adjustment)
                throw new Exception("Gemini AI returned text response instead of image data");
            }

            throw new Exception("No content generated by Gemini AI");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error calling Gemini AI");
            throw new Exception($"Gemini AI call failed: {ex.Message}");
        }
    }

    private string CreatePrompt(AvatarRequest request)
    {
        return $@"
        Generate a photorealistic avatar portrait based on these exact specifications:

        PHYSICAL ATTRIBUTES:
        - Height: {request.Height}
        - Weight: {request.Weight}
        - Body Type: {request.BodyType}
        - Skin Tone: {request.SkinTone}
        - Hair Color: {request.HairColor}
        - Hair Style: {request.HairStyle}
        - Eye Color: {request.EyeColor}

        ADDITIONAL REQUIREMENTS:
        {request.AdditionalSpecifications}

        IMAGE SPECIFICATIONS:
        - Style: Professional portrait photography
        - Format: Shoulders and above framing
        - Background: Soft, neutral gradient background
        - Lighting: Natural, professional studio lighting
        - Expression: Neutral or slightly friendly expression
        - Quality: High resolution, photorealistic
        - Perspective: Front-facing, professional headshot
        - Age: Adult appearance (25-40 years)
        - Attire: Professional clothing (business casual)

        IMPORTANT: Create a realistic, professional-looking avatar that appears natural and suitable for professional profiles. Ensure diverse and inclusive representation.
        ";
    }

    private async Task<string> UploadToAzureBlobStorage(byte[] imageBytes, string fileName)
    {
        var containerName = _configuration["AzureStorage:ContainerName"] ?? "avatars";
        var containerClient = _blobServiceClient.GetBlobContainerClient(containerName);

        // Create container if it doesn't exist
        await containerClient.CreateIfNotExistsAsync(PublicAccessType.Blob);

        var blobClient = containerClient.GetBlobClient(fileName);

        using var stream = new MemoryStream(imageBytes);
        await blobClient.UploadAsync(stream, new BlobUploadOptions
        {
            HttpHeaders = new BlobHttpHeaders
            {
                ContentType = "image/png"
            }
        });

        _logger.LogInformation($"Image uploaded to Azure Blob Storage: {blobClient.Uri}");
        return blobClient.Uri.ToString();
    }

    [HttpGet("test-connection")]
    public async Task<IActionResult> TestConnections()
    {
        try
        {
            // Test Azure Storage connection
            var containerName = _configuration["AzureStorage:ContainerName"] ?? "avatars";
            var containerClient = _blobServiceClient.GetBlobContainerClient(containerName);
            await containerClient.CreateIfNotExistsAsync(PublicAccessType.None);

            // Test Gemini AI connection (simplified)
            var geminiModel = _configuration["GeminiAI:Model"] ?? "imagen-3.0-generate-002";

            return Ok(new
            {
                azureStorage = "Connected",
                geminiAI = "Configured",
                model = geminiModel
            });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new { error = ex.Message });
        }
    }
}

public class AvatarRequest
{
    public string Height { get; set; } = string.Empty;
    public string Weight { get; set; } = string.Empty;
    public string BodyType { get; set; } = string.Empty;
    public string SkinTone { get; set; } = string.Empty;
    public string HairColor { get; set; } = string.Empty;
    public string HairStyle { get; set; } = string.Empty;
    public string EyeColor { get; set; } = string.Empty;
    public string AdditionalSpecifications { get; set; } = string.Empty;
}

public class AvatarResponse
{
    public string ImageUrl { get; set; } = string.Empty;
}